name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Build the app
        run: scripts/buildprod.sh

      - name: Decode and write GCP credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 -d > "${{ github.workspace }}/gcloud-key.json"

      - name: Dump raw JSON (sanitized)
        run: |
          sed -n l "${{ github.workspace }}/gcloud-key.json"

      - name: Check JSON validity
        run: |
          jq . "${{ github.workspace }}/gcloud-key.json"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcloud-key.json"
          gcloud config set project notely-460310

      - name: Who am I?
        run: gcloud auth list

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image (gcloud build submit)
        run: |
          docker build -t us-central1-docker.pkg.dev/notely-460310/notely-ar-repo/notely:latest .
          docker push us-central1-docker.pkg.dev/notely-460310/notely-ar-repo/notely:latest
